folio-org/ui-myprofile

package.json

Move permissionSets into the stripes object in package.json.

---

translations/ui-myprofile/ar.json

Update translation strings as of 20181031T224505

---

translations/ui-myprofile/pt_PT.json

Update translation strings as of 20181212T135930

---

translations/ui-myprofile/zh_CN.json

Update translation strings as of 20190108T192353

---

translations/ui-myprofile/en_SE.json

Update translation strings as of 20190110T173959

---

package.json

Change Permission Name: 
"My profile: Can view settings for users profile" 
**TO** 
"My profile: Can change your local password"

UIU-831: Change permission name.

---

translations/ui-myprofile/en_US.json

Update translation strings as of 20190211T033248

---

translations/ui-myprofile/it_IT.json

Update translation strings as of 20190312T123958

---

translations/ui-myprofile/es_419.json

Update translation strings as of 20190422T163602

---

translations/ui-myprofile/it_IT.json

Update translation strings as of 20190918T144452

---

translations/ui-myprofile/ru.json
translations/ui-myprofile/zh_TW.json

Update translation strings as of 20191014T135140

---

translations/ui-myprofile/ja.json

Update translation strings as of 20191028T205642

---

settings/ChangePassword/ChangePasswordForm.css
settings/ChangePassword/ChangePasswordForm.js

Move save button to the footer.
https://issues.folio.org/browse/UIMPROF-38

UIMPROF-38 - My Profile | Move Save button to the footer 

---

translations/ui-myprofile/ru.json

Update translation strings as of 20191111T233434

---

translations/ui-myprofile/he.json

Update translation strings as of 20191114T012425

---

translations/ui-myprofile/it_IT.json

Update translation strings as of 20191115T154823

---

translations/ui-myprofile/fr_FR.json
translations/ui-myprofile/it_IT.json

Update translation strings as of 20191122T140350

---

translations/ui-myprofile/fr_FR.json

Update translation strings as of 20191125T160504

---

translations/ui-myprofile/ru.json

Update translation strings as of 20191204T162855

---

translations/ui-myprofile/en_SE.json

Update translation strings as of 20191220T210632

---

translations/ui-myprofile/ur.json

Update translation strings as of 20200210T220102

---

translations/ui-myprofile/fr_FR.json

Update translation strings as of 20200302T163727

---

package.json

Not sure how I missed this in #102.

update peer-dep to stripes v3

---

translations/ui-myprofile/ja.json

Update translation strings as of 20200413T183215

---

translations/ui-myprofile/ja.json

Update translation strings as of 20200415T223222

---

translations/ui-myprofile/zh_TW.json

Update translation strings as of 20200424T193712

---

CHANGELOG.md
package.json

Updating `react-intl` to `^4.5.1`
https://issues.folio.org/browse/STRIPES-672

STRIPES-672: Update react-intl version

---

translations/ui-myprofile/zh_TW.json

Update translation strings as of 20200513T135229

---

translations/ui-myprofile/en_SE.json
translations/ui-myprofile/en_US.json

Update translation strings as of 20200527T144757

---

translations/ui-myprofile/fr_FR.json

Update translation strings as of 20200604T202430

---

translations/ui-myprofile/ru.json

Update translation strings as of 20200626T180122

---

CHANGELOG.md
package.json

Refs [UIMPROF-47](https://issues.folio.org/browse/UIMPROF-47)

UIMPROF-47 increment react-intl to v5

---

CHANGELOG.md
package.json

* `@folio/stripes`
* `react-router`
* `react-intl`
Because everybody wants to be just like Tom Hanks, Alec Baldwin, Steve
Martin.

five-ify all the things

---

translations/ui-myprofile/pl.json

Update translation strings as of 20200924T211627

---

CHANGELOG.md
translations/ui-myprofile/en.json

Add missing permission descriptions to translation files
[UIMPROF-49](https://issues.folio.org/browse/UIMPROF-49)

UIMPROF-49: Add missing permission translation

---

translations/ui-myprofile/ar.json
translations/ui-myprofile/ca.json
translations/ui-myprofile/da.json
translations/ui-myprofile/de.json
translations/ui-myprofile/en_GB.json
translations/ui-myprofile/en_SE.json
translations/ui-myprofile/en_US.json
translations/ui-myprofile/es.json
translations/ui-myprofile/es_419.json
translations/ui-myprofile/es_ES.json
translations/ui-myprofile/fr.json
translations/ui-myprofile/fr_FR.json
translations/ui-myprofile/he.json
translations/ui-myprofile/hi_IN.json
translations/ui-myprofile/hu.json
translations/ui-myprofile/it_IT.json
translations/ui-myprofile/ja.json
translations/ui-myprofile/ko.json
translations/ui-myprofile/pl.json
translations/ui-myprofile/pt_BR.json
translations/ui-myprofile/pt_PT.json
translations/ui-myprofile/ru.json
translations/ui-myprofile/ur.json
translations/ui-myprofile/zh_CN.json
translations/ui-myprofile/zh_TW.json

Update translation strings as of 20201013T203429

---

translations/ui-myprofile/es.json
translations/ui-myprofile/es_419.json
translations/ui-myprofile/es_ES.json

Update translation strings as of 20201016T144229

---

translations/ui-myprofile/zh_CN.json

Update translation strings as of 20201030T134930

---

translations/ui-myprofile/ber.json

Update translation strings as of 20201109T135508

---

translations/ui-myprofile/ja.json

Update translation strings as of 20201124T212804

---

CHANGELOG.md
PERSONAL_DATA_DISCLOSURE.md

Added personal data disclosure form

UIMPROF-54: Add personal data disclosure form

---

CHANGELOG.md
Jenkinsfile
package.json

Issue: [UIMPROF-57](https://issues.folio.org/browse/UIMPROF-57)

UIMPROF-57: Compile Translation Files into AST Format

---

CHANGELOG.md
package.json

increment stripes to v7 and react to v17
[UIMPROF-60](https://issues.folio.org/browse/UIMPROF-60)

UIMPROF-60: increment stripes to v7

---

CHANGELOG.md
package.json
test/jest/__mock__/stripesConfig.mock.js
test/jest/babel.config.js
test/jest/jest.setup.js

Fix Jest tests run problems.
This PR contains all necessary changes to make possible to run Jest tests, and resolve some eslint warnings. Changes was proposed by @zburke (thanks him a lot).
https://issues.folio.org/browse/UIMPROF-65

UIMPROF-63: Fix Jest tests run problems

---

package.json

Reverts folio-org/ui-myprofile#188

Revert "Revert "FOLIO-3477 : FE: update outdated dependencies""

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json

Issue: update NodeJS to v16 in GitHub Actions
https://issues.folio.org/browse/UIMPROF-71

UIMPROF-71 : update NodeJS to v16 in GitHub Actions

---

CHANGELOG.md
src/settings/ChangePassword/ChangePasswordForm.js

Purpose: https://issues.folio.org/browse/UIMPROF-76

UIMPROF-76 Save button remains enabled despite validation errors on My profile form

---

CHANGELOG.md
package.json

bump stripes to 8.0.0 for Orchid/2023-R1
[UIMPROF-77](https://issues.folio.org/browse/UIMPROF-77)

UIMPROF-77 bump stripes to 8.0.0 for Orchid/2023-R1

---

CHANGELOG.md
PULL_REQUEST_TEMPLATE.md

Add PULL_REQUEST_TEMPLATE.md file to the repository.
https://issues.folio.org/browse/UIMPROF-81

UIMPROF-81 - Add pull request template md file

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md

[UIMPROF-85](https://issues.folio.org/browse/UIMPROF-85) - Update Node.js to v18 in GitHub Actions
Run command grep -rl "NODEJS_VERSION: '16'" .github | xargs perl -pi -e "s/NODEJS_VERSION: '16'/NODEJS_VERSION: '18'/g" as described in the ticket.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UIMPROF-85 - Update Node.js to v18 in GitHub Actions

---

.eslintrc.js
CHANGELOG.md
package.json
src/settings/MyProfile.js

This PR is intended for Poppy release.
Fix eslint config.
Fix eslint issue.
Update change log

Release v9.0.0

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UIMPROF-90
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …

Release v9.1.0

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md

[UIMPROF-93](https://folio-org.atlassian.net/browse/UIMPROF-93) - Upgrade version for `actions/upload-artifact` from v2 to v4.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

UIMPROF-93 - Upgrade version for `actions/upload-artifact` from v2 to v4.

---

CHANGELOG.md
package.json

This PR intends to **release ui-myprofile for Ramsons.**
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to …

Release v9.2.0

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UIMPROF-101; https://folio-org.atlassian.net/browse/UIMPROF-102

UIMPROF-101, UIMPROF-102: migrate stripes-* deps; react-intl to v7

---

.github/CODEOWNERS.txt

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify potential problems, ensuring that it's …

Add codeowners
